---
title: "Part 1"
---

## Revision Recap

Need a hint? [Review the slides here!](https://docs.google.com/presentation/d/11RdaC-vg1TZgoLgenjkgaNJ0pZ4j4h1qUmxxmZPmWgM/edit?usp=sharing)

```{r, child="../child/data_design.qmd"}

```

```{r}
source("../scripts/revision_script.R")
```

## Output

```{r}
cat("Model 1: Productivity predicted by coffee consumption")
model1
```

## Tasks

```{r, child="../child/p1_tasks.qmd"}

```

For the following questions, match up the equation of the line to the corresponding scatterplot.

```{r}
lm_mat
```

`r paste0("_____ ", 1:4, ". y~i~ = ", round(mods_sum$b0, 2)," + ", round(mods_sum$b1, 2), "x~i~ + e~i~", sep = "\n\n", collapse = "")`

## Solutions

[Review the solutions slides here](https://docs.google.com/presentation/d/1GoO61HU75qGDb38pwSG-TSufFp0yp7wyM5kodCyL8sI/edit?usp=sharing).

\ 

<a href="https://and-rev.netlify.app/"><button class="button">« Back to Home</button></a> <a href="https://and-rev.netlify.app/opt1/bbw1"><button class="button right">Next Section »</button></a>
